name: Prod / 3. Publish release from latest version

on:
  workflow_dispatch:
    inputs:
      target:
        type: choice
        description: "릴리즈 대상 선택"
        required: true
        options:
          - all
          - web only
jobs:
  publish:
    name: test 
    runs-on: ubuntu-latest
    steps:
      - name: Send Curl Request
        run: |
          curl -X POST -H "Content-type: application/json" \
          --data '{"text":"Hello, World"}' \
          "https://hook.swit.io/chat/240524042739561X6IOV/hkQuH7HE5R41aOmrawLR?organization_id=19090600325683321"
      - name: a1 test
        if: github.event.inputs.target == 'all'
        run: |
          echo source clone ...
      - name: a2 test
        if: ${{github.event.inputs.target == 'all'}}
        run: |
          echo source clone ...
