name: action-test!!

on:
  pull_request:
    branches:
      - '*'
    types:
      - opened
      - edited
jobs:
  action-test:
    name: test 
    runs-on: [ self-hosted, ARM64, macOS ]
    steps:
      - name: Hello world action step
        id: test-action
        uses: swit-fe/swit-github-action@0.1
      - name: Checkout
        uses: actions/checkout@v4
      - name: action!!
        uses: ./src/actions/sendMessageToPrReviewers
      
