name: Prod / Version Bump

on:
  workflow_dispatch:
    inputs:
      release:
        type: string
        description: "Check the version of master. (ex: 1.0.0)"
        required: true
      target:
        type: choice
        description: "Select a package to bump."
        required: true
        options:
          - common
          - auth
          - ui
          - emoji
      bumpTo:
        type: string
        description: "Bump to. (ex: 1.0.0)"
        required: true

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: 'https://npm.pkg.github.com'
      - name: gulp 설치
        run:
          npm i gulp@4.0.2 -g
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get App version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
      - name: Check App Version
        run: |
          VERSION="${{steps.package-version.outputs.current-version}}"
          echo "$VERSION"
      - name: Create a branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'chores/bump_${{github.event.inputs.target}}_to_${{github.event.inputs.bumpTo}}'
      - name: Checkout chores/bump_${{github.event.inputs.target}}_to_${{github.event.inputs.bumpTo}}
        uses: actions/checkout@v3
        with: 
          ref: chores/bump_${{github.event.inputs.target}}_to_${{github.event.inputs.bumpTo}}
      - name: Create test
        run:
          npm run test -- bumpTo=14.1.00000 -- target=test
        env:
          NODE_AUTH_TOKEN: ${{secrets.DEV_EXPRESS_REPO_AND_PACKAGE_TOKEN}}
      - name: test add and commit
        uses: EndBug/add-and-commit@v9
        with: 
          message: 'chore: bump ${{github.event.inputs.target}} to ${{github.event.inputs.bumpTo}}'
      - name: Create PR
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: 'chore: bump ${{github.event.inputs.target}} to ${{github.event.inputs.bumpTo}}'
          source_branch: chores/bump_${{github.event.inputs.target}}_to_${{github.event.inputs.bumpTo}}
          destination_branch: master
          pr_assignee: ${{github.actor}}


    

    
