name: Prod / 3. Publish release from latest version

on:
  workflow_dispatch:
    inputs:
      target:
        type: choice
        description: "릴리즈 대상 선택"
        required: true
        options:
          - all
          - web only
jobs:
  publish:
    name: test 
    runs-on: [ self-hosted, X64, macOS ]
    steps:
      - name: a1 test
        if: github.event.inputs.check == 'all'
        run: |
          echo source clone ...
      - name: a2 test
        if: ${{github.event.inputs.check == 'all'}}
        run: |
          echo source clone ...
