name: Prod / Version Bump

on:
  workflow_dispatch:
    inputs:
      release:
        type: string
        description: "Check the version of master. (ex: 1.0.0)"
        required: true
      target:
        type: choice
        description: "Select a package to bump."
        required: true
        options:
          - common
          - auth
          - ui
          - emoji
      bumpTo:
        type: string
        description: "Bump to. (ex: 1.0.0)"
        required: true

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Create a branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'chores/bump_${{github.event.inputs.target}}_to_${{github.event.inputs.bumpTo}}'
      - name: Checkout chores/bump_${{github.event.inputs.target}}_to_${{github.event.inputs.bumpTo}}
        uses: actions/checkout@v3
        with: 
          ref: chores/bump_${{github.event.inputs.target}}_to_${{github.event.inputs.bumpTo}}
      - name: Create test file
        uses: finnp/create-file-action@master
        env:
          FILE_NAME: "./bump_${{github.event.inputs.target}}_to_${{github.event.inputs.bumpTo}}.txt"
          FILE_DATA: "file content"
      - name: test add and commit
        uses: EndBug/add-and-commit@v9
        with: 
          message: 'chore: bump ${{github.event.inputs.target}} to ${{github.event.inputs.bumpTo}}'
      - name: Create PR
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'chore: bump ${{github.event.inputs.target}} to ${{github.event.inputs.bumpTo}}'
          branch: 'chores/bump_${{github.event.inputs.target}}_to_${{github.event.inputs.bumpTo}}'



    

    
