name: Dev / Deployment Builder (dev & express)

on:
  workflow_dispatch:
    inputs:
      domain:
        type: choice
        description: "Select a domain to deploy."
        required: true
        options:
          - production
          - express
      branch:
        type: string
        description: "Other Branch(Optional)"
        required: false
      silent:
        type: boolean
        required: false
        description: "Skip Logging"

jobs:
  deploy:
    name: Build "${{needs.check-branch.outputs.branch}}" branch to "app.swit.${{github.event.inputs.domain}}".
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: _$(Date:yyyyMMdd)
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - name: install npm 8
        run: npm i -g npm@8 --registry=https://registry.npmjs.org
      - name: Install Dependencies
        run: npm i
      - name: Angular Build
        run: npm run build --configuration=${{github.event.inputs.domain}}
